// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ── GLOBAL AI INVOKE GUARD ────────────────────────────────────────────────────
// Block any edge-function invocation whose name contains AI-related keywords.
// This is the final client-side safety net; edge functions also enforce this.
const AI_BLOCKED_PATTERNS = /ai|assistant|generate|suggest/i;
const _originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = (functionName: string, options?: Parameters<typeof _originalInvoke>[1]) => {
  const payload = (options as any)?.body ?? {};
  if (AI_BLOCKED_PATTERNS.test(functionName)) {
    console.warn(`[AI GUARD] Blocked invoke: "${functionName}" — AI_ENABLED=false`);
    // Fire-and-forget trace log for blocked calls
    supabase.from("runtime_traces" as any).insert({
      source: "frontend",
      function_name: functionName,
      endpoint: "blocked",
      error_message: "AI BLOCKED",
      payload_snapshot: payload,
      created_at: new Date().toISOString(),
    }).then(() => {}).catch(() => {});
    return Promise.resolve({ data: null, error: new Error('AI_DISABLED') });
  }
  // Fire-and-forget trace log for allowed calls
  supabase.from("runtime_traces" as any).insert({
    source: "frontend",
    function_name: functionName,
    endpoint: "invoke",
    error_message: null,
    payload_snapshot: payload,
    created_at: new Date().toISOString(),
  }).then(() => {}).catch(() => {});
  return _originalInvoke(functionName, options);
};
// ─────────────────────────────────────────────────────────────────────────────