// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// ── Global invoke guard ──────────────────────────────────────────────────────
// Logs every edge-function call and hard-blocks any AI/generate/suggest
// function from being invoked (prevents unexpected AI credit usage).
const _originalInvoke = supabase.functions.invoke.bind(supabase.functions);
supabase.functions.invoke = async (fn: string, payload?: any) => {
  console.warn('[INVOKE]', fn, payload ?? {});

  if (fn.includes('ai') || fn.includes('generate') || fn.includes('suggest')) {
    const msg = `BLOCKED_AT_INVOKE_LAYER: "${fn}" is an AI function and must not be called automatically`;
    console.error('[AI CALL BLOCKED]', fn);
    throw new Error(msg);
  }

  return _originalInvoke(fn, payload);
};